### ISSUE TITLE
Enabling secure communication TLS for rabbitmq

### ISSUE THREAD

**Issue by jdartland** [eiffel-community/eiffel-event-repository#13] opened 2022-12-12 09:51 UTC
### Description

Currently, we are using eiffel repository through the docker image[ eiffel-er:2.0.36](https://hub.docker.com/layers/eiffelericsson/eiffel-er/2.0.36/images/sha256-8b63ef1a720a8497128045d103304378cc76639ab596325a370dc6160d602d74?context=explore). We want to configure the event repository to use secure communication over TLS when consuming events from RabbitMq. We have the TSL port 5671 configured in rabbitmq. For other eiffel components, such as eiffel-intelligence(backend), it has been possible to enable rabbitmq TLS communication, simply just by setting the following environment variables:

```
rabbitmq.tls.version=TLSv1.2
rabbitmq.port=5671
```

However, this does not seems to have any effect on the eiffel-event-repository component as it fails to connect to the rabbitmq broker with the following error:

2022-12-12 09:28:15.761 ERROR 6 --- [ost-startStop-1] c.e.e.m.consumer.MessageBusBinder        : Eiffel/MessageBusBinder: Exception creating connection to Message Bus IOException:
2022-12-12 09:28:15.762 ERROR 6 --- [ost-startStop-1] c.e.e.rmq.consumer.RmqConnectionHandler  : java.lang.IllegalArgumentException: The connection must not be null!connection to message bus amqp://<hostnamehere>:5671 failed

We suspect the component contains some configuration that tries to connect with amqp instead of amqps. As it is not open-sourced yet we, would appreciate some more information on how to set up the secure connection to the broker properly.

Thanks :)

**Comment by jainadc9** [comment] 2023-03-30 06:45
Reproduced issue with eiffel-er:2.0.37 ,enabled rabbtmq.tls flag to true still issue is observed

**Comment by jainadc9** [comment] 2023-08-02 12:23
It doesn't matter if we specify "amqp" or "amqps" in rabbitmq.host since it is the javax.net.ssl.* and eiffel.net.ssl.protocol system properties that determines SSL or not!

**Comment by jainadc9** [comment] 2024-06-05 11:40
Need to enable the following java opts to enable secure er.The following is a snippet from docker-compose file 

```
  environment:                   
       - |
         JAVA_OPTS=
         "-Djavax.net.ssl.keyStore=/path/to/keystore.jks"
         "-Djavax.net.ssl.trustStore=/path/to/truststore.jks"
         "-Djavax.net.ssl.keyStorePassword=password"
         "-Djavax.net.ssl.trustStorePassword=password" 
         "-Djavax.net.ssl.keyStoreType=JKS"
         "-Djavax.net.ssl.trustStoreType=JKS"
         "-Deiffel.net.ssl.enabled=true"
       - rabbitmq.port=5671
       - rabbitmq.tls=true
``` 



Option to debug ssl  "-Djavax.net.debug=ssl"

**Comment by jainadc9** [comment] 2024-06-07 05:27
@jdartland can you verify the above configuration so that we can close this issue ?

**Comment by m-linner-ericsson** [comment] 2024-08-14 12:11
@jdartland Any thoughts?

**Comment by m-linner-ericsson** [comment] 2024-10-09 13:29
We propose to close this ticket. @jdartland any objections? You can always open it again if you are not satisfied with the solution.

**Comment by m-linner-ericsson** [comment] 2024-11-06 09:46
Closing this issue due to lack of response. Please feel free to open it again if needed.

**Closed as completed by m-linner-ericsson** 2024-11-06 09:46 UTC
